# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OpenTAKServer Documentation
theme:
  name: windmill
  search_index_only: true
  include_search_page: true
plugins:
  - glightbox
extra:
  version: 1.0
  article_nav_top: false
  article_nav_bottom: false
  history_buttons: false
repo_url: https://github.com/brian7704/OpenTAKServer
site_url: https://docs.opentakserver.io
edit_uri: https://github.com/brian7704/OpenTAKServer-docs/tree/master/docs
nav:
  - Home: 'index.md'
  - Installation:
    - Installer: 'installation/installation.md'
    - Manual Installation: 'installation/manual_installation.md'
  - Configuration: 'configuration.md'
  - Database: 'database.md'
  - Secrets: 'secrets.md'
  - CoT Routing: 'cot_routing.md'
  - Certificate Enrollment: 'certificate_enrollment.md'
  - Email: 'email.md'
  - Authentication: 'authentication.md'
  - API: 'API.md'
  - ADS-B: 'adsb.md'
  - Mumble: 'mumble.md'
  - Symbology: 'symbology.md'
  - Video Streaming: 'video_streaming.md'
  - Public Server: 'public_server.md'
  - OpenTAK ICU:
    - OpenTAK ICU: 'opentak_icu/index.md'
    - Streaming Protocols: 'opentak_icu/streaming_protocols.md'
    - Audio Codecs: 'opentak_icu/audio_codecs.md'
    - Video Codecs: 'opentak_icu/video_codecs.md'
    - Encryption: 'opentak_icu/encryption.md'
    - TAK Server: 'opentak_icu/tak_server.md'
    - MediaMTX: 'opentak_icu/mediamtx.md'