# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OpenTAKServer Documentation
theme:
  name: windmill
extra:
  version: 1.0
  article_nav_top: false
  article_nav_bottom: false
  history_buttons: true
repo_url: https://github.com/brian7704/OpenTAKServer
site_url: https://docs.opentakserver.io
nav:
  - Home: 'index.md'
  - Installation:
    - Installer: 'installation/installation.md'
    - Manual Installation: 'installation/manual_installation.md'
  - Certificate Enrollment: 'certificate_enrollment.md'
  - API: 'API.md'
  - ADS-B: 'adsb.md'